version: '3.5'

# 服务容器配置
services:
  nginx: # 自定义容器名称
    restart: always
    container_name: nginx # 容器名称
    image: nginx
    environment: # 设置环境变量
      - TZ=Asia/Shanghai
    volumes:
      - /home/myservers/conf.d:/etc/nginx/conf.d
      - /home/myservers/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    network_mode: host