version: '3.5'

# 服务容器配置
services:

  myservers_web: # 自定义容器名称
    container_name: myservers_web # 容器名称
    build:
      context: ./
      dockerfile: Dockerfile
    environment: # 设置环境变量
      - TZ=Asia/Shanghai
    privileged: true
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    network_mode: host
    restart: always                      # 指定容器退出后的重启策略为始终重启