name: 编译并推送到腾讯云

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.17.1]
    steps:
    - uses: actions/checkout@v3
    - name: 设置node环境
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm ci
      run: npm ci
    - name: 编译
      run: npm run build
    - name: 上传构建产物
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: ['43.138.184.162']
    steps:
    - uses: actions/checkout@v3
    - name: 下载构建产物
      uses: actions/download-artifact@v2
      with:
        name: build
    - name: 上传到服务器
      uses: appleboy/scp-action@master
      with:
        host: ${{ matrix.server }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: './build'
        target: '/home/myservers/conf.d/myservers/web'
    - name: 上传配置
      uses: appleboy/scp-action@master
      with:
        host: ${{ matrix.server }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: './myservers.conf'
        target: '/home/myservers/conf.d'
    - name: 上传nginx.conf和docker-compose.yaml
      uses: appleboy/scp-action@master
      with:
        host: ${{ matrix.server }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: './nginx.conf,./docker-compose.yaml'
        target: '/home/myservers'
    - name: 重启服务
      uses: appleboy/ssh-action@master
      with:
        host: ${{ matrix.server }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/myservers
          docker-compose up -d
          docker-compose restart
